### PR TITLE
Accept custom folder icons like Dolphin and Konqueror do.

### PR DESCRIPTION
**Pull request by tsujan**
This makes PCManFM-qt read the file ".directory" inside a folder (if it exists) and set the icon of that folder accordingly, as is the case with Dolphin and Konqueror.

For now, PCManFM-qt doesn't do anything when the folder icon on the Properties dialog is clicked but the ".directory" file can be created manually or by a simple file-manager action.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Some brief comments describing the larger block would be nice. Other than that, GTM.

**Comment by tsujan** [comment]
@paulolieuthier  Oh, sorry for the delay! It seems that I missed an email notification.

Here, before setting the icon of a folder (`S_ISDIR(st.st_mode)`), the GLib counterpart of QSettings (`GKeyFile`) is used for reading the file `.directory` inside that folder (`dot_dir`) and finding the value of the key `Icon` under `Desktop Entry` (`g_key_file_get_string()`). If there is a valid icon, it'll be used for the folder in question; otherwise, the default folder icon will be used.

The value of `Icon` could be a valid icon name or a full icon path.

I use it often with a custom action since I made this PR and it's very fast. It's handy with icon sets that include various `places` icons. All folders, whose icons are customized in KDE, are also shown correctly by pcmanfm-qt.

**Comment by paulolieuthier** [comment]
I meant comments in the code. :)

**Comment by tsujan** [comment]
> I meant comments in the code.

Already added ;)

**Comment by gcavallo** [comment]
Another solution would be to send directories to the thumbnailers in `/usr/share/thumbnailers`. This currently works out of the box for pcmanfm-qt but requires a [libfm patch](https://sourceforge.net/p/pcmanfm/bugs/1020/) for pcmanfm-gtk. Here's a shameless plug for a [thumbnailer in bash](https://github.com/gcavallo/pcmanfm-covers).

Of course a native implementation like this pull request seems better, most certainly faster. Any reasons why this hasn't been merged yet?

**Comment by tsujan** [comment]
> Of course a native implementation like this pull request seems better, most certainly faster

I use it for a year and have seen no impact on pcmanfm-qt's responsiveness at all.

> Any reasons why this hasn't been merged yet?

Everything is slow with libfm -- I say this based on experience.

**Comment by gcavallo** [comment]
I just tried your commit on pcmanfm-gtk2 and it's really fast! Got 150 covers in a snap. It even works with the patch I linked above, the thumbnailer kicks in after to take priority.

One little thing is that it doesn't support relative paths like Dolphin does with `./` paths. That said the FreeDesktop specification says `Icon` should be an absolute path or an icon-theme target, so your commit is standards-compliant.

**Comment by ivy-b** [comment]
This looks great. I have compiled it but I don't know how to get pcmanfm to use it.

Can you tell me how to ./configure pcmanfm to used my patched libfm please?

**Comment by tsujan** [comment]
Done by https://github.com/lxde/libfm-qt/commit/6b8cc2e8791c042495276df7ca6817f3bb88eba6 more consistently. Closing this.

**Comment by gcavallo** [comment]
So custom folder icons will only work for QT but not GTK? I've been using this PR for months so I'm a little puzzled why GTK is disregarded.

**Comment by tsujan** [comment]
@gcavallo I work on pcmanfm-qt, not the gtk based pcmanfm. On the one hand, for whatever reason, libfm PRs aren't reviewed here, let alone merged. On the other hand, this part of libfm-qt became independent of libfm months ago, so that this patch didn't have any effect on pcmanfm-qt.

Anyhow, you're familiar with the patch and could make another PR but, as you can see by a glance at the date of this patch, it might not be reviewed until 2020 ;)

**Pull request closed without merging**
