### PR TITLE
Add 'Mail to' feature

### PR DESCRIPTION
**Pull request by phileimer**

### CODE REVIEW

**Comment by LStranger** [comment]
Nice looking feature, although it would be good to test for `xdg-utils` executable to hide this item if it's not available.

**Comment by LStranger** [comment]
Do you know that you can add this feature without any changes of pcmanfm code? Just add a file with content
```
[Desktop Entry]
Name = Mail-To ...
Profiles = MailTo;
TryExec = xdg-email
[X-Action-Profile MailTo]
Exec = xdg-email --attach %F
```
as `~/.local/share/file-manager/actions/mailto.desktop` and you'll get it in context menu immediately.

**Comment by LStranger** [comment]
It's better to be implemented as an user action. Thank you.

**Comment by phileimer** [comment]
Hi @LStranger 
Thank you for this tip!

**Pull request closed without merging**
